LIB = libbio.a
LOBJ = bbuffered.o \
	bfildes.o \
	bflush.o \
	bgetc.o \
	bgetd.o \
	bgetrune.o \
	binit.o \
	boffset.o \
	bprint.o \
	bvprint.o \
	bputc.o \
	bputrune.o \
	brdline.o \
	brdstr.o \
	bread.o \
	bseek.o bwrite.o

LOCAL_CFLAGS = -I"$PREFIX"/include -I.
DEPS = libutf libfmt

<$mkbuild/mk.default

