BIN = pax
pax_OBJ = ar_io.o ar_subs.o buf_subs.o cache.o cpio.o file_subs.o ftree.o \
        gen_subs.o getoldopt.o options.o pat_rep.o pax.o sel_subs.o tables.o \
        tar.o tty_subs.o
INSTALL_BIN = pax
INSTALL_SYMLINK = pax tar
DEPS = libcommon

<$mkbuild/mk.default
