BIN = pax
pax_OBJ = ar_io.o ar_subs.o buf_subs.o cache.o cpio.o file_subs.o ftree.o \
        gen_subs.o getoldopt.o options.o pat_rep.o pax.o sel_subs.o tables.o \
        tar.o tty_subs.o
INSTALL_BIN = pax
INSTALL_SYMLINK = \
	pax /bin/tar \
	pax /bin/cpio
INSTALL_MAN1 = pax.1 tar.1 cpio.1
DEPS = libcommon

<$mkbuild/mk.default
