LIB = libutf.a
LOBJ = \
	rune.o\
	runestrcat.o\
	runestrchr.o\
	runestrcmp.o\
	runestrcpy.o\
	runestrdup.o\
	runestrlen.o\
	runestrecpy.o\
	runestrncat.o\
	runestrncmp.o\
	runestrncpy.o\
	runestrrchr.o\
	runestrstr.o\
	runetype.o\
	utfecpy.o\
	utflen.o\
	utfnlen.o\
	utfrrune.o\
	utfrune.o\
	utfutf.o\

LOCAL_CFLAGS = -I"$PREFIX"/include

<$mkbuild/mk.default

