BIN = nawk
OBJ = awk.lx.o b.o lib.o main.o parse.o proctab.o run.o tran.o \
	awk.g.o version.o
LOCAL_CFLAGS = -DSU3
LOCAL_LDFLAGS = -lm
CLEAN_FILES = maketab maketab.o awk.g.c y.tab.h awk.lx.c proctab.c awk.1
DEPS = libcommon libuxre lex yacc ed

<$mkbuild/mk.common

INSTALL_BIN = nawk
INSTALL_MAN1 = nawk.1
INSTALL_SYMLINK = \
	nawk $BINDIR/awk \
	nawk.1 $MANDIR/man1/awk.1

nawk: $OBJ

awk.g.c:Q: awk.g.y
	echo YACC $target
	$YACC -d awk.g.y
	mv -f y.tab.c awk.g.c

y.tab.h:Q: awk.g.c
	(echo '1i'; echo '#include <inttypes.h>'; echo '.'; echo 'w';) | \
		$ED -s y.tab.h

maketab:Q: maketab.o
	echo CC $target
	$CC $LDFLAGS maketab.o -o maketab

proctab.c: maketab
	./maketab > proctab.c
	
awk.lx.c:Q: awk.lx.l
	echo LEX $target
	$LEX -t awk.lx.l > awk.lx.c

maketab.o:Q: maketab.c
	echo CC $target
	$CC -DIN_MAKETAB -c maketab.c

awk.g.o: awk.h y.tab.h
awk.lx.o: awk.h y.tab.h
b.o: awk.h y.tab.h
lib.o: awk.h y.tab.h
main.o: awk.h y.tab.h
maketab.o: awk.h y.tab.h
parse.o: awk.h y.tab.h
proctab.o: awk.h y.tab.h
run.o: awk.h y.tab.h
tran.o: awk.h y.tab.h
version.o: awk.h y.tab.h
