BIN = mk
OBJ = \
	arc.o\
	archive.o\
	bufblock.o\
	env.o\
	file.o\
	graph.o\
	job.o\
	lex.o\
	main.o\
	match.o\
	mk.o\
	parse.o\
	recipe.o\
	rc.o\
	rule.o\
	run.o\
	sh.o\
	shell.o\
	shprint.o\
	symtab.o\
	var.o\
	varsub.o\
	word.o\
	unix.o\

LOCAL_CFLAGS = -I"$PREFIX"/include
LOCAL_LDFLAGS = -L"$PREFIX"/lib
INSTALL_BIN = mk
INSTALL_MAN1 = mk.1
DEPS = libbio libfmt libutf libregexp

<$mkbuild/mk.default

